parameters:
  dotNetCoreInstallerVersion: '2.2.300'
  pool: 'Default'
  extraArguments: ''

stages:
- stage: build
  jobs:
  - job: build
    displayName: 'Run Build'
    pool: ${{ parameters.pool }}
      #vmImage: 'windows-latest'
    steps:
    - task: GitVersion@4
      inputs:
        preferBundledVersion: true

    - task: DotNetCoreInstaller@0
      inputs:
        version: ${{ parameters.dotNetCoreInstallerVersion }}

    #- task: NuGetToolInstaller@0 # Doesn't require exact Version live above task

    - task: DotNetCoreCLI@2
      displayName: 'Restore'
    #  inputs:
    #    command: 'restore'
    #    #projects: '**/*.csproj'
    #    feedsToUse: 'select'    

    - task: DotNetCoreCLI@2
      displayName: 'Build'
      inputs:
        command: 'build'
        arguments: '${{ parameters.extraArguments }} --configuration $(BuildConfiguration)'

    - task: variabledehydration@0
      inputs:
        prefixes: 'GITVERSION,BUILD'
        outpath: '$(build.artifactstagingdirectory)/vars'

    - task: PublishPipelineArtifact@0
      displayName: 'Publish Artifact drop'
      inputs:
        artifactName: 'vars'
        targetPath: '$(build.artifactstagingdirectory)/vars'

    - task: PublishPipelineArtifact@0
      displayName: 'Publish Artifact drop'
      inputs:
        artifactName: 'drop'
        targetPath: '$(Build.SourcesDirectory)'