parameters:
  stageName: 'Deploy'
  stageDisplayName: 'Deploy'
  jobName: 'NugetPack'
  jobDisplayName: 'Pack Nuget'
  pool: 'Default'
  artifactName: 'nuget'
  environment: ''
  azurePublishJobName: 'DeployNugetAzureArtifacts'
  azurePublishJobDisplayName: 'Deploy Preview to Azure Artifacts'
  azureDevOpsOrg: ''
  azureDevOpsFeed: ''
  azureIslegacyDevOpsUrl: false
  azureNugetServerApiVersion: 'v3'
  allowPackageConflicts: true
  nugetPublishJobName: 'DeployNuget'
  nugetPublishJobDisplayName: 'Deploy to Nuget'
  nuGetServiceConnections: ''
  nugetApiKeyVar: ''
  nugetPackageVersion: ''
  
stages:
- stage: ${{ parameters.stageName }}
  displayName: ${{ parameters.stageDisplayName }}
  jobs:
  - job: ${{ parameters.jobName }}
    displayName: ${{ parameters.jobDisplayName }}
    pool: ${{ parameters.pool }}
    steps:
    - checkout: none
    - template: ../steps/load-build-variables.yml
    - task: DownloadPipelineArtifact@1
      inputs:
        artifactName: 'drop'
        targetPath: '$(Build.SourcesDirectory)'
   
    - template: ../steps/nuget-pack.yml
      parameters:
        artifactName: ${{ parameters.artifactName }}

  - template: ../jobs/nuget-deploy-to-azureArtifacts.yml
    parameters:
      jobName: ${{ parameters.azurePublishJobName }}
      jobDisplayName: ${{ parameters.azurePublishJobDisplayName }}
      pool: ${{ parameters.pool }}
      environment: ${{ parameters.environment }}
      artifactName: ${{ parameters.artifactName }}
      azureDevOpsOrg: ${{ parameters.azureDevOpsOrg }}
      azureDevOpsFeed: ${{ parameters.azureDevOpsFeed }}
      azureIslegacyDevOpsUrl: ${{ parameters.azureIslegacyDevOpsUrl }}
      azureNugetServerApiVersion: ${{ parameters.azureNugetServerApiVersion }}
      allowPackageConflicts: ${{ parameters.allowPackageConflicts }}

  - template: ../jobs/nuget-deploy-to-nuget.yml
    parameters:
      jobName: ${{parameters.nugetPublishJobName }}
      jobDisplayName: ${{ parameters.nugetPublishJobDisplayName }}
      pool: ${{ parameters.pool }}
      environment: ${{ parameters.environment }}
      artifactName: ${{ parameters.artifactName }}
      nuGetServiceConnections: ${{ parameters.azureNuGetServiceConnections }}
      allowPackageConflicts: ${{ parameters.allowPackageConflicts }}
      nugetPackageVersion: ${{ parameters.nugetPackageVersion }}
      publishFeedCredentials: ${{parameters.publishFeedCredentials }}
      

          