parameters:
  jobName: 'DeployNugetAzureArtifacts'
  jobDdisplayName: 'Deploy to Azure Artifacts'
  pool: 'Default'
  artifactName: 'nuget'
  publishVstsFeed: ''
  allowPackageConflicts: true
  azureDevOpsOrg: ''
  environment: 'AzureArtifacts'

jobs:
  - deployment: ${{ parameters.jobName }}
    displayName: ${{ parameters.jobDisplayName }}
    pool: ${{ parameters.pool }}
    variables:
        nugetVersion: "t"
    environment: ${{ parameters.environment }}
    strategy:
      runOnce:
        deploy:
          steps:
          - task: DownloadPipelineArtifact@1
            inputs:
              artifactName: ${{ parameters.artifactName }}
              targetPath: $(Build.ArtifactStagingDirectory)
          
          - task: NuGetAuthenticate@0
          - task: NuGetToolInstaller@1

          - task: Powershell@2
            name: nuGetPush
            displayName: 'Nuget Push'
            inputs:
              targetType: inline
              script: |
                 nuget push -ApiKey AzurePipeline -Source https://pkgs.dev.azure.com/${{ parameters.azureDevOpsOrg }}/_packaging/${{ parameters.publishVstsFeed }}/nuget/v3/index.json $(Build.ArtifactStagingDirectory)/**/*.nupkg -NoSymbols -SkipDuplicate ${{ parameters.allowPackageConflicts }}
    condition: > 
      and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'), 
        or(eq(variables['Build.SourceBranch'], 'refs/heads/master'),
          startswith(variables['Build.SourceBranch'], 'refs/heads/release/'),
          startswith(variables['Build.SourceBranch'], 'refs/heads/azure-pipelines-test')) )
