parameters:
  jobName: 'DeployNuget'
  jobDisplayName: 'Deploy to Nuget'
  pool: 'Default'
  environment: 'NuGet_Org'
  artifactName: 'nuget'
  nugetToolVersion: ''
  #nuGetServiceConnections: ''
  apiKeyVar: ~
  serverApiVersion:
  packagesGlob: ~
  allowPackageConflicts: true

jobs:
  - deployment: ${{ parameters.jobName }}
    displayName: ${{ parameters.jobDisplayName }}
    pool: ${{ parameters.pool }}
    environment: ${{ parameters.environment }}
    strategy:
      runOnce:
        deploy:
          steps:
          - template: ../steps/nuget-push.yml
            parameters:
              artifactName: ${{ parameters.artifactName }}
              nugetToolVersion: ${{ parameters.nugetToolVersion }}
              apiKeyVar: ${{ coalesce(parameters.apiKeyVar, '$(nuGet_Org_ApiKey)' ) }} 
              serverApiVersion: ${{ parameters.serverApiVersion }}
              packagesGlob: ${{ parameters.packagesGlob }}
              allowPackageConflicts: ${{ parameters.allowPackageConflicts }}
    condition: > 
      and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'), 
        or(eq(variables['Build.SourceBranch'], 'refs/heads/master'),
          startswith(variables['Build.SourceBranch'], 'refs/heads/release/'),
          startswith(variables['Build.SourceBranch'], 'refs/heads/azure-pipelines-test')) )