parameters:
  jobName: 'DeployNugetAzureArtifacts'
  jobDdisplayName: 'Deploy to Azure Artifacts'
  pool: 'Default'
  environment: 'AzureArtifacts'
  artifactName: 'nuget'
  azureDevOpsOrg: ''
  publishDevOpsFeed: ''
  islegacyDevOpsUrl: false
  nugetServerApiVersion: 'v3'
  allowPackageConflicts: true

jobs:
  - deployment: ${{ parameters.jobName }}
    displayName: ${{ parameters.jobDisplayName }}
    pool: ${{ parameters.pool }}
    variables:
        nugetVersion: "t"
    environment: ${{ parameters.environment }}
    strategy:
      runOnce:
        deploy:
          steps:
          - task: DownloadPipelineArtifact@1
            inputs:
              artifactName: ${{ parameters.artifactName }}
              targetPath: $(Build.ArtifactStagingDirectory)
          
          - task: NuGetAuthenticate@0
          - task: NuGetToolInstaller@1

          - task: Powershell@2
            name: nuGetPush
            displayName: 'Nuget Push'
            env:
              org: ${{ parameters.azureDevOpsOrg }}
              feed: ${{ parameters.publishDevOpsFeed }}
              isLegacyUrl: ${{ parameters.islegacyDevOpsUrl }}
              apiVersion: ${{ parameters.nugetServerApiVersion }}
              skipDiplicate: ${{ parameters.allowPackageConflicts }}
            inputs:
              targetType: inline
              script: |
                $orgUrl = '';
                
                Write-Verbose "isLegacyUrl:- $env:isLegacyUrl" -Verbose;
                Write-Verbose "isLeacyUrl true:- $env:isLegacyUrl -eq $true" -Verbose;

                if($env:isLegacyUrl -eq $true)
                {
                  $orgUrl = "$env:ORG.pkgs.visualstudio.com"
                } else
                {
                  $orgUrl = "pkgs.dev.azure.com/$env:ORG"
                }

                Write-Verbose "url:- https://$orgUrl/_packaging/$env:FEED/nuget/$env:APIVERSION/index.json" -Verbose;

                nuget push -ApiKey AzurePipeline -Source https://$orgUrl/_packaging/$env:FEED/nuget/$env:APIVERSION/index.json `
                 $(Build.ArtifactStagingDirectory)/**/*.nupkg -NoSymbols -SkipDuplicate $env:SKIPDUPLICATE
    condition: > 
      and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'), 
        or(eq(variables['Build.SourceBranch'], 'refs/heads/master'),
          startswith(variables['Build.SourceBranch'], 'refs/heads/release/'),
          startswith(variables['Build.SourceBranch'], 'refs/heads/azure-pipeline')) )
